/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#bd9dff',
        'primary-dim':                '#8a4cfc',
        'primary-fixed':              '#b28cff',
        'primary-fixed-dim':          '#a67aff',
        'primary-container':          '#b28cff',
        'on-primary':                 '#3c0089',
        'on-primary-fixed':           '#000000',
        'on-primary-container':       '#2e006c',
        'on-primary-fixed-variant':   '#390083',
        'secondary':                  '#a88cfb',
        'secondary-dim':              '#a88cfb',
        'secondary-fixed':            '#d8caff',
        'secondary-fixed-dim':        '#ccbaff',
        'secondary-container':        '#4f319c',
        'on-secondary':               '#260069',
        'on-secondary-fixed':         '#3c1989',
        'on-secondary-container':     '#d7c8ff',
        'on-secondary-fixed-variant': '#593ca6',
        'tertiary':                   '#ff97b2',
        'tertiary-dim':               '#f17799',
        'tertiary-fixed':             '#ff8eac',
        'tertiary-fixed-dim':         '#f77c9e',
        'tertiary-container':         '#fe81a4',
        'on-tertiary':                '#6a0a31',
        'on-tertiary-fixed':          '#380016',
        'on-tertiary-container':      '#5a0027',
        'on-tertiary-fixed-variant':  '#711036',
        'surface':                    '#0d0d18',
        'surface-dim':                '#0d0d18',
        'surface-bright':             '#2b2a3c',
        'surface-variant':            '#242434',
        'surface-tint':               '#bd9dff',
        'surface-container':          '#181826',
        'surface-container-low':      '#12121e',
        'surface-container-high':     '#1e1e2d',
        'surface-container-highest':  '#242434',
        'surface-container-lowest':   '#000000',
        'on-surface':                 '#e9e6f7',
        'on-surface-variant':         '#aba9b9',
        'on-background':              '#e9e6f7',
        'background':                 '#0d0d18',
        'outline':                    '#757482',
        'outline-variant':            '#474754',
        'inverse-surface':            '#fcf8ff',
        'inverse-on-surface':         '#555461',
        'inverse-primary':            '#742fe5',
        'error':                      '#ff6e84',
        'error-dim':                  '#d73357',
        'error-container':            '#a70138',
        'on-error':                   '#490013',
        'on-error-container':         '#ffb2b9',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body:     ['Plus Jakarta Sans', 'sans-serif'],
        label:    ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
