const PDFDocument = require('pdfkit');

function buildPDF(content, meta, res) {
  const doc = new PDFDocument({ margin: 60, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="assignment-${meta.topic.replace(/\s+/g, '-')}.pdf"`
  );

  doc.pipe(res);

  doc.rect(0, 0, doc.page.width, 100).fill('#1a1a2e');

  doc.fillColor('#a78bfa').fontSize(20).font('Helvetica-Bold').text('AI TUTOR', 60, 30);
  doc.fillColor('#ffffff').fontSize(11).font('Helvetica').text('AI-Powered Assignment', 60, 55);
  doc.fillColor('#a78bfa').fontSize(9).text(`Generated: ${new Date().toLocaleDateString()}`, 60, 75);

  doc.moveDown(3);

  doc.fillColor('#1a1a2e').roundedRect(60, doc.y, doc.page.width - 120, 60, 8).fill();

  doc
    .fillColor('#ffffff')
    .fontSize(16)
    .font('Helvetica-Bold')
    .text(content.title || `${meta.topic} Assignment`, 80, doc.y - 48);

  doc
    .fillColor('#a78bfa')
    .fontSize(10)
    .font('Helvetica')
    .text(`${meta.gradeLevel} Level  - ${meta.type} - Topic: ${meta.topic}`, 80, doc.y - 25);

  doc.moveDown(2);

  doc
    .fillColor('#374151')
    .fontSize(10)
    .font('Helvetica')
    .text('Name: ___________________________   Date: _______________   Score: _______ / 10', 60);

  doc.moveDown(1);
  drawLine(doc);
  doc.moveDown(1);

  sectionHeader(doc, 'Learning Objectives');
  doc
    .fillColor('#374151')
    .fontSize(11)
    .font('Helvetica')
    .text(content.objectives || '', 60, doc.y, { width: doc.page.width - 120 });

  doc.moveDown(1.5);
  drawLine(doc);
  doc.moveDown(1);

  sectionHeader(doc, 'Questions');

  const questions = content.questions || [];
  questions.forEach((q, i) => {
    doc.moveDown(0.5);

    doc
      .fillColor('#1a1a2e')
      .fontSize(11)
      .font('Helvetica-Bold')
      .text(`${i + 1}. ${q.question}`, 60, doc.y, { width: doc.page.width - 120 });

    if (q.type === 'mcq' && q.options) {
      doc.moveDown(0.3);
      q.options.forEach((opt) => {
        doc.fillColor('#374151').fontSize(10).font('Helvetica').text(`    ${opt}`, 70, doc.y, {
          width: doc.page.width - 130,
        });
      });
    } else {
      doc.moveDown(0.5);
      for (let l = 0; l < 3; l += 1) {
        doc
          .moveTo(70, doc.y + 5)
          .lineTo(doc.page.width - 60, doc.y + 5)
          .strokeColor('#d1d5db')
          .lineWidth(0.5)
          .stroke();
        doc.moveDown(0.8);
      }
    }

    doc.moveDown(0.5);
  });

  doc.moveDown(1);
  drawLine(doc);
  doc.moveDown(1);

  sectionHeader(doc, 'Answer Key (Teacher Use Only)');

  doc
    .fillColor('#374151')
    .fontSize(10)
    .font('Helvetica')
    .text(content.answerKey || '', 60, doc.y, { width: doc.page.width - 120 });

  const pageBottom = doc.page.height - 40;
  doc
    .moveTo(60, pageBottom - 15)
    .lineTo(doc.page.width - 60, pageBottom - 15)
    .strokeColor('#e5e7eb')
    .lineWidth(0.5)
    .stroke();

  doc.fillColor('#9ca3af').fontSize(8).text('Generated by AI Tutor App', 60, pageBottom - 5);

  doc.end();
}

function sectionHeader(doc, text) {
  doc.fillColor('#7c3aed').fontSize(13).font('Helvetica-Bold').text(text, 60);
  doc.moveDown(0.5);
}

function drawLine(doc) {
  doc
    .moveTo(60, doc.y)
    .lineTo(doc.page.width - 60, doc.y)
    .strokeColor('#e5e7eb')
    .lineWidth(0.5)
    .stroke();
}

module.exports = buildPDF;
